# Generated by Django 4.2.3 on 2023-08-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitr_drive', '0002_folder_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='folder',
            name='description',
            field=models.TextField(default='Add Description'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
