# Generated by Django 4.2.3 on 2023-09-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitr_drive', '0003_remove_folder_date_posted_folder_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('file', models.FileField(upload_to='Files')),
            ],
        ),
    ]
