# Generated by Django 4.2.3 on 2023-09-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iitr_drive', '0005_file_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='title',
            new_name='filetitle',
        ),
    ]
