# Generated by Django 4.2.3 on 2023-09-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitr_drive', '0006_rename_title_file_filetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='linked_in',
            field=models.BigIntegerField(default=-1),
        ),
    ]
