# Generated by Django 4.2.3 on 2023-09-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitr_drive', '0007_folder_linked_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
