# Generated by Django 4.2.3 on 2023-09-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iitr_drive', '0009_folder_parent_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
    ]
