# Generated by Django 4.2.3 on 2023-09-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iitr_drive', '0012_sharelink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShareLink',
        ),
    ]
