# Generated by Django 4.2.3 on 2023-09-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitr_drive', '0013_delete_sharelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filetitle',
            field=models.CharField(default='File', max_length=55),
        ),
    ]
