# Generated by Django 4.2.3 on 2024-12-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iitr_drive', '0014_alter_file_filetitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderRelationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='iitr_drive.folder')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='iitr_drive.folder')),
            ],
        ),
    ]
