# Generated by Django 4.2.3 on 2024-12-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iitr_drive', '0015_folderrelationtable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folderrelationtable',
            unique_together={('parent', 'child')},
        ),
    ]
