# Generated by Django 4.2.3 on 2024-12-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iitr_drive', '0016_alter_folderrelationtable_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
    ]
