# Generated by Django 4.2.3 on 2024-12-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iitr_drive', '0017_remove_folder_parent_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='linked_in',
            new_name='parent_id',
        ),
    ]
